default_ui = "gitui"
repo_name = "default"

[ui_config.lazygit]
additional_args = ""
repo_path_arg_name = "--path"

[ui_config.gitkraken]
repo_path_arg_name = "--path"
additional_args = ""

[ui_config.gitui]
additional_args = "--watcher --logging"
repo_path_arg_name = "--directory"

[files.nixos]
"/home/o/projects/new/dotup/README.md" = "/home/o/projects/new/dotup/README.md"
